import React, { useState } from 'react';
import { 
  Sparkles, 
  TrendingUp, 
  Calendar, 
  Sun, 
  CloudRain, 
  Cloud,
  ChevronRight,
  TrendingDown,
  LineChart,
  BrainCircuit,
  Droplets,
  AlertOctagon,
  RefreshCw
} from 'lucide-react';
import { Field, WeatherForecast } from '../types';
import { WEATHER_FORECAST } from '../data';

interface DeepDiveProps {
  activeField: Field;
  indexType: string;
}

export default function DeepDive({ activeField, indexType }: DeepDiveProps) {
  const [timeRange, setTimeRange] = useState<'3M' | '6M' | '1Y'>('3M');
  const [analyzing, setAnalyzing] = useState<boolean>(false);
  
  // Real Gemini Insights state
  const [aiReport, setAiReport] = useState<string>("");
  const [loadingAi, setLoadingAi] = useState<boolean>(false);
  const [isFallback, setIsFallback] = useState<boolean>(false);

  // Quick Action States
  const [activeAdviceModal, setActiveAdviceModal] = useState<string | null>(null);

  const triggerAnalysis = () => {
    setAnalyzing(true);
    setTimeout(() => {
      setAnalyzing(false);
      alert(`Precision analytical scan complete for ${activeField.name}. System scanned Sentinel-2 L2A data bands and verified multi-temporal change curves.`);
    }, 1500);
  };

  const fetchGeminiReport = async () => {
    setLoadingAi(true);
    setAiReport("");
    setIsFallback(false);

    try {
      const response = await fetch("/api/gemini-analysis", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          fieldName: activeField.name,
          crop: activeField.crop,
          ndvi: activeField.ndvi,
          soilPh: activeField.soilPh,
          soilNitrogen: activeField.soilNitrogen,
          soilOrganicCarbon: activeField.soilOrganicCarbon,
          growthStage: activeField.growthStage,
          weather: WEATHER_FORECAST[0] // send today's weather
        })
      });

      const data = await response.json();
      setAiReport(data.advice || "No report generated.");
      setIsFallback(!!data.isFallback);
    } catch (err) {
      console.error(err);
      setAiReport("Error connecting to agronomic server.");
    } finally {
      setLoadingAi(false);
    }
  };

  // Inline formatting helper for Markdown generated by Gemini
  const renderMarkdown = (text: string) => {
    if (!text) return null;
    
    // Split into lines and parse headers/bold text simply
    return text.split('\n').map((line, idx) => {
      let trimmed = line.trim();
      if (trimmed.startsWith('### ')) {
        return <h4 key={idx} className="text-sm font-bold text-[#2A4B35] mt-4 mb-2">{trimmed.replace('### ', '')}</h4>;
      }
      if (trimmed.startsWith('## ')) {
        return <h3 key={idx} className="text-base font-serif font-bold text-[#1A1A1A] mt-5 mb-2">{trimmed.replace('## ', '')}</h3>;
      }
      if (trimmed.startsWith('# ')) {
        return <h2 key={idx} className="text-lg font-serif font-bold text-[#2A4B35] mt-6 mb-3">{trimmed.replace('# ', '')}</h2>;
      }
      if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        const item = trimmed.substring(2);
        return (
          <li key={idx} className="text-xs text-black/80 ml-4 list-disc list-outside mb-1.5 leading-relaxed">
            {parseBoldText(item)}
          </li>
        );
      }
      return <p key={idx} className="text-xs text-black/70 leading-relaxed mb-3">{parseBoldText(trimmed)}</p>;
    });
  };

  const parseBoldText = (text: string) => {
    const parts = text.split(/\*\*(.*?)\*\*/g);
    return parts.map((part, i) => i % 2 === 1 ? <strong key={i} className="text-[#2A4B35] font-semibold">{part}</strong> : part);
  };

  // Simulated quick alerts
  const showAdviceDetail = (type: 'irrigation' | 'harvest') => {
    if (type === 'irrigation') {
      setActiveAdviceModal(
        `💧 Irrigation Advisory: Current weather is warm (28°C) with a low probability of rain (12%). The NDMI (Moisture Index) shows mild transpiration stress. We recommend applying 25mm of uniform overhead water on Friday evening to reduce soil moisture vaporization losses.`
      );
    } else {
      setActiveAdviceModal(
        `📅 Harvest Window Planning: Current satellite NDVI trends suggest physiological maturity will be completed in approximately 12 days. Optimal harvest parameters exist between October 12 and October 18, pending local weather stability.`
      );
    }
  };

  return (
    <main className="md:ml-80 pt-20 px-6 pb-12 min-h-screen bg-[#F5F5F0] text-[#1A1A1A]">
      
      {/* Header section with telemetry sync metadata */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4 border-b border-black/10 pb-6">
        <div>
          <h1 className="font-serif text-3xl font-bold text-[#1A1A1A] mb-1">
            Analytical Deep-Dive: {activeField.name}
          </h1>
          <div className="flex items-center gap-3">
            <span className="px-2 py-0.5 bg-[#2A4B35]/10 border border-[#2A4B35]/20 text-[#2A4B35] font-mono text-[9px] rounded uppercase font-semibold">
              SENTINEL-2 LIVE
            </span>
            <span className="text-black/60 text-xs font-mono">Last sync: 14 mins ago</span>
          </div>
        </div>

        <button 
          onClick={triggerAnalysis}
          className="bg-[#2A4B35] text-white px-5 py-2 rounded-xl font-mono text-xs uppercase font-bold tracking-wider hover:bg-[#3E654C] active:scale-95 transition-all flex items-center gap-2 cursor-pointer shadow-sm"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${analyzing ? 'animate-spin' : ''}`} />
          <span>New Analysis</span>
        </button>
      </div>

      {/* Bento Grid layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 mb-8">
        
        {/* Card 1: NDVI Vegetation Stress Index (90 Days) SVG chart */}
        <div className="lg:col-span-8 glass-panel p-5 rounded-2xl relative overflow-hidden bg-white border border-black/10">
          <div className="flex justify-between items-center mb-6">
            <h3 className="font-mono text-[10px] text-black/60 tracking-widest uppercase font-bold">
              {indexType.toUpperCase()} Vegetation Stress Index (90 Days)
            </h3>
            <div className="flex gap-2">
              {(['3M', '6M', '1Y'] as const).map((r) => (
                <button
                  key={r}
                  onClick={() => setTimeRange(r)}
                  className={`py-1 px-3 text-[10px] font-mono rounded-full transition-colors cursor-pointer ${
                    timeRange === r 
                      ? 'bg-[#F5F5F0] text-[#1A1A1A] border border-black/10 font-bold' 
                      : 'text-black/60 hover:bg-black/5'
                  }`}
                >
                  {r}
                </button>
              ))}
            </div>
          </div>

          {/* Custom SVG Line Chart matching mockup screens */}
          <div className="h-64 md:h-72 w-full relative">
            <div className="absolute inset-0 flex items-end justify-between px-2 pb-6 border-b border-l border-black/10">
              
              <svg className="absolute inset-0 w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 400 200">
                {/* Gradient area underneath line */}
                <defs>
                  <linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#2A4B35" stopOpacity="0.15" />
                    <stop offset="100%" stopColor="#2A4B35" stopOpacity="0" />
                  </linearGradient>
                </defs>
                <path 
                  d="M 0 160 Q 40 140 80 150 T 160 120 T 240 80 T 320 60 T 400 70" 
                  fill="none" 
                  stroke="#2A4B35" 
                  strokeWidth="2.5" 
                />
                <path 
                  d="M 0 160 Q 40 140 80 150 T 160 120 T 240 80 T 320 60 T 400 70 L 400 200 L 0 200 Z" 
                  fill="url(#chartGradient)"
                />

                {/* Simulated historical coordinate dots */}
                <circle cx="80" cy="150" r="4.5" className="fill-[#2A4B35] stroke-white stroke-2 cursor-pointer hover:r-6 transition-all" title="June 15: 0.42" />
                <circle cx="160" cy="120" r="4.5" className="fill-[#2A4B35] stroke-white stroke-2 cursor-pointer hover:r-6 transition-all" title="July 1: 0.58" />
                <circle cx="240" cy="80" r="4.5" className="fill-[#2A4B35] stroke-white stroke-2 cursor-pointer hover:r-6 transition-all" title="July 15: 0.69" />
                <circle cx="320" cy="60" r="4.5" className="fill-[#2A4B35] stroke-white stroke-2 cursor-pointer hover:r-6 transition-all" title="August 1: 0.78" />
              </svg>

              {/* Grid lines */}
              <div className="absolute inset-0 flex flex-col justify-between pointer-events-none opacity-5">
                <div className="border-t border-black w-full"></div>
                <div className="border-t border-black w-full"></div>
                <div className="border-t border-black w-full"></div>
                <div className="border-t border-black w-full"></div>
              </div>

            </div>
          </div>

          {/* X-axis indicators */}
          <div className="flex justify-between mt-4 text-[10px] font-mono text-black/60 uppercase tracking-wider">
            <span>Jun 01</span>
            <span>Jul 15</span>
            <span>Aug 30</span>
          </div>
        </div>

        {/* Card 2: Yield Projection */}
        <div className="lg:col-span-4 glass-panel p-5 rounded-2xl flex flex-col border-l-4 border-l-[#2A4B35] bg-white border border-black/10">
          <div className="flex items-start justify-between mb-4">
            <h3 className="font-mono text-[10px] text-black/60 tracking-widest uppercase font-bold">Yield Projection</h3>
            <TrendingUp className="text-[#2A4B35] w-5 h-5" />
          </div>
          
          <div className="flex flex-col flex-1 justify-center py-6 text-center">
            <p className="text-5xl font-extrabold text-[#1A1A1A] leading-none font-mono">
              {activeField.yieldProjection.toFixed(1)}
            </p>
            <p className="font-mono text-[10px] text-black/60 uppercase tracking-widest mt-2">Tons / Hectare</p>
          </div>

          <div className="mt-auto space-y-3">
            <div className="flex justify-between items-center text-xs">
              <span className="text-black/60">Confidence Rating</span>
              <span className="text-emerald-700 font-bold font-mono">94.2%</span>
            </div>
            <div className="h-1.5 w-full bg-black/10 rounded-full overflow-hidden">
              <div className="h-full bg-[#2A4B35] w-[94.2%] transition-all duration-1000"></div>
            </div>
            <p className="text-[11px] text-black/60 italic leading-relaxed">
              Projection optimized by multi-spectral transpiration index patterns and regional rainfall projections for Sept-Oct.
            </p>
          </div>
        </div>

        {/* Card 3: Gemini AI Advisory Intelligence Module */}
        <div className="lg:col-span-8 glass-panel p-5 rounded-2xl bg-white border border-black/10 relative overflow-hidden">
          
          {/* Decorative brain neural path backdrop */}
          <div className="absolute top-2 right-2 opacity-5 pointer-events-none">
            <BrainCircuit className="w-48 h-48 text-[#2A4B35]" />
          </div>

          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 mb-5 relative z-10">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-full bg-[#2A4B35]/10 flex items-center justify-center">
                <Sparkles className="text-[#2A4B35] w-4.5 h-4.5" />
              </div>
              <h3 className="font-serif text-sm text-[#1A1A1A] font-bold">
                Gemini Agricultural Advisory
              </h3>
            </div>

            <button 
              onClick={fetchGeminiReport}
              disabled={loadingAi}
              className="bg-[#2A4B35] hover:bg-[#3E654C] text-white font-mono text-[10px] font-bold uppercase tracking-wider py-1.5 px-4 rounded-lg flex items-center gap-1.5 disabled:opacity-50 active:scale-98 transition-all cursor-pointer shadow-sm"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>{loadingAi ? "Analyzing Field..." : "✨ Run AI Advisory"}</span>
            </button>
          </div>

          {/* Advisory Content Blocks */}
          <div className="relative z-10 grid grid-cols-1 md:grid-cols-2 gap-6 min-h-[12rem]">
            {loadingAi ? (
              <div className="col-span-2 flex flex-col justify-center items-center py-12 space-y-3">
                <RefreshCw className="text-[#2A4B35] w-8 h-8 animate-spin" />
                <p className="font-mono text-[10px] text-black/60 uppercase tracking-wider">Agri AI Consulting satellite bands & soil data...</p>
              </div>
            ) : aiReport ? (
              <div className="col-span-2 bg-[#F5F5F0] border border-black/10 rounded-xl p-4 max-h-80 overflow-y-auto space-y-2 select-text text-left">
                {isFallback && (
                  <div className="flex items-center gap-2 p-2 bg-amber-600/10 border border-amber-600/20 text-amber-900 rounded-lg mb-2 text-[10px] font-mono">
                    <AlertOctagon className="w-4 h-4 shrink-0" />
                    <span>Using high-fidelity pre-computed agricultural logic (Config a secret GEMINI_API_KEY in Settings for custom live AI).</span>
                  </div>
                )}
                {renderMarkdown(aiReport)}
              </div>
            ) : (
              <>
                <div className="space-y-4 text-left">
                  <div className="p-3.5 bg-[#2A4B35]/5 border-l-2 border-[#2A4B35] rounded-r-xl">
                    <p className="text-xs font-bold text-[#2A4B35] mb-1">
                      {activeField.ndvi < 0.5 ? "Nitrogen Deficit Identified" : "Foliar Density Intact"}
                    </p>
                    <p className="text-[11px] text-black/70 leading-relaxed">
                      {activeField.ndvi < 0.5 
                        ? `West quadrant displaying sub-optimal chlorophyll synthesis. Consider variable-rate Nitrogenous (N) top-dress at 22 kg/ha.`
                        : `Vigour levels correspond to optimal vegetative mass. No immediate chemical top-dress correction is recommended.`
                      }
                    </p>
                  </div>
                  
                  <div className="p-3.5 bg-amber-600/5 border-l-2 border-amber-600/40 rounded-r-xl">
                    <p className="text-xs font-bold text-amber-800 mb-1">Pest Vector Prediction Window</p>
                    <p className="text-[11px] text-black/70 leading-relaxed">
                      Peak relative humidity parameters forecasted. Protective foliar scanning is recommended within 72 hours for potential aphid or spore infestation.
                    </p>
                  </div>
                </div>

                <div className="flex flex-col justify-center gap-3">
                  <div 
                    onClick={() => showAdviceDetail('irrigation')}
                    className="flex items-center gap-4 p-4 glass-panel rounded-xl hover:border-black/20 transition-colors cursor-pointer bg-[#F5F5F0] border border-black/5 shadow-sm"
                  >
                    <Droplets className="text-[#2A4B35] w-5 h-5 shrink-0" />
                    <div className="text-left">
                      <p className="text-[11px] font-bold uppercase tracking-wider text-[#1A1A1A]">Optimize Irrigation</p>
                      <p className="text-[10px] text-black/60">Apply 25mm crop moisture topup</p>
                    </div>
                  </div>

                  <div 
                    onClick={() => showAdviceDetail('harvest')}
                    className="flex items-center gap-4 p-4 glass-panel rounded-xl hover:border-black/20 transition-colors cursor-pointer bg-[#F5F5F0] border border-black/5 shadow-sm"
                  >
                    <Calendar className="text-[#2A4B35] w-5 h-5 shrink-0" />
                    <div className="text-left">
                      <p className="text-[11px] font-bold uppercase tracking-wider text-[#1A1A1A]">Harvest Planning Window</p>
                      <p className="text-[10px] text-black/60">Projected: Oct 12 – 18</p>
                    </div>
                  </div>
                </div>
              </>
            )}
          </div>

          {/* Quick Action Advisory Modal Detail inline overlay */}
          {activeAdviceModal && (
            <div className="absolute inset-0 bg-white/95 z-30 p-6 flex flex-col justify-center items-center text-center space-y-4">
              <div className="w-12 h-12 rounded-full bg-[#2A4B35]/10 flex items-center justify-center text-[#2A4B35]">
                <Sparkles className="w-6 h-6" />
              </div>
              <p className="text-sm text-black/80 max-w-md leading-relaxed">{activeAdviceModal}</p>
              <button 
                onClick={() => setActiveAdviceModal(null)}
                className="py-1.5 px-4 bg-[#2A4B35] text-white font-mono text-[10px] uppercase font-bold rounded-lg cursor-pointer hover:bg-[#3E654C] transition-colors"
              >
                Close Insights
              </button>
            </div>
          )}

        </div>

        {/* Card 4: Local Weather Forecast (72h) */}
        <div className="lg:col-span-4 flex flex-col gap-6">
          <div className="glass-panel p-5 rounded-2xl flex-1 bg-white border border-black/10">
            <h3 className="font-mono text-[10px] text-black/60 mb-4 uppercase tracking-widest font-bold">Local Weather (72h)</h3>
            
            <div className="space-y-3.5">
              {WEATHER_FORECAST.map((w, idx) => (
                <div key={idx} className="flex items-center justify-between p-3 bg-[#F5F5F0] rounded-xl border border-black/5 hover:border-black/15 transition-colors">
                  <div className="flex items-center gap-3">
                    {w.icon === 'sun' || w.icon === 'sunny' ? (
                      <Sun className="text-amber-500 w-5 h-5" />
                    ) : (
                      <Cloud className="text-[#2A4B35] w-5 h-5" />
                    )}
                    <div className="text-left font-mono">
                      <p className="text-[11px] font-bold text-[#1A1A1A]">{w.day}</p>
                      <p className="text-[9px] text-black/60">{w.condition}</p>
                    </div>
                  </div>

                  <div className="text-right font-mono">
                    <p className="text-sm font-bold text-[#1A1A1A]">{w.temp}°C</p>
                    <p className="text-[9px] text-emerald-800">{w.rainProb}% Rain</p>
                  </div>
                </div>
              ))}
            </div>

          </div>
        </div>

      </div>

      {/* Soil Property Gauges row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* pH Level Ring Gauge */}
        <div className="glass-panel p-5 rounded-2xl flex flex-col items-center bg-white border border-black/10">
          <h4 className="font-mono text-[10px] text-black/60 mb-4 uppercase tracking-widest font-bold">Soil pH Level</h4>
          <div className="relative w-32 h-32 flex items-center justify-center select-none">
            <svg className="w-full h-full transform -rotate-90">
              <circle className="text-black/5" cx="64" cy="64" fill="transparent" r="54" stroke="currentColor" strokeWidth="8"></circle>
              <circle 
                className="text-[#2A4B35]" 
                cx="64" 
                cy="64" 
                fill="transparent" 
                r="54" 
                stroke="currentColor" 
                strokeWidth="8"
                strokeDasharray="339"
                strokeDashoffset={339 - (339 * (activeField.soilPh / 14))}
                strokeLinecap="round"
              ></circle>
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center font-mono">
              <span className="text-3xl font-extrabold text-[#1A1A1A] leading-none">{activeField.soilPh}</span>
              <span className="text-[9px] font-bold text-emerald-800 mt-1.5 uppercase">OPTIMAL</span>
            </div>
          </div>
          <p className="font-mono text-[10px] text-black/60 mt-4">Last sampled: 3 days ago</p>
        </div>

        {/* Nitrogen Ring Gauge */}
        <div className="glass-panel p-5 rounded-2xl flex flex-col items-center bg-white border border-black/10">
          <h4 className="font-mono text-[10px] text-black/60 mb-4 uppercase tracking-widest font-bold">Nitrogen (N)</h4>
          <div className="relative w-32 h-32 flex items-center justify-center select-none">
            <svg className="w-full h-full transform -rotate-90">
              <circle className="text-black/5" cx="64" cy="64" fill="transparent" r="54" stroke="currentColor" strokeWidth="8"></circle>
              <circle 
                className="text-amber-600" 
                cx="64" 
                cy="64" 
                fill="transparent" 
                r="54" 
                stroke="currentColor" 
                strokeWidth="8"
                strokeDasharray="339"
                strokeDashoffset={339 - (339 * (activeField.soilNitrogen / 200))}
                strokeLinecap="round"
              ></circle>
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center font-mono">
              <span className="text-3xl font-extrabold text-[#1A1A1A] leading-none">{activeField.soilNitrogen}</span>
              <span className="text-[9px] font-bold text-amber-700 mt-1.5 uppercase">MODERATE</span>
            </div>
          </div>
          <p className="font-mono text-[10px] text-black/60 mt-4">kg/ha availability</p>
        </div>

        {/* Organic Carbon Ring Gauge */}
        <div className="glass-panel p-5 rounded-2xl flex flex-col items-center bg-white border border-black/10">
          <h4 className="font-mono text-[10px] text-black/60 mb-4 uppercase tracking-widest font-bold">Organic Carbon</h4>
          <div className="relative w-32 h-32 flex items-center justify-center select-none">
            <svg className="w-full h-full transform -rotate-90">
              <circle className="text-black/5" cx="64" cy="64" fill="transparent" r="54" stroke="currentColor" strokeWidth="8"></circle>
              <circle 
                className="text-[#2A4B35]" 
                cx="64" 
                cy="64" 
                fill="transparent" 
                r="54" 
                stroke="currentColor" 
                strokeWidth="8"
                strokeDasharray="339"
                strokeDashoffset={339 - (339 * (activeField.soilOrganicCarbon / 5))}
                strokeLinecap="round"
              ></circle>
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center font-mono">
              <span className="text-3xl font-extrabold text-[#1A1A1A] leading-none">{activeField.soilOrganicCarbon}%</span>
              <span className="text-[9px] font-bold text-emerald-800 mt-1.5 uppercase">HEALTHY</span>
            </div>
          </div>
          <p className="font-mono text-[10px] text-black/60 mt-4">Surface layer (0-15cm)</p>
        </div>

      </div>

    </main>
  );
}
